### ISSUE TITLE
Wyze is changing its authentication method.

### ISSUE THREAD

**Issue by bunnyc1986** [jfarmer08/homebridge-wyze-smart-home#105]
**Is your feature request related to a problem? Please describe:**
I received an email notifying us Wyze is changing its authentication method to API keys. I think the plugin needs an upgrade accordingly.

**Describe the solution you'd like:**
Switch to API key authencation in the plugin config.

**Describe alternatives you've considered:**
N/A

**Additional context:**
The Wyze blog post: https://support.wyze.com/hc/en-us/articles/16129834216731?lid=87ac6t8mqos0

**Comment by ourstanley** [comment]
So I've installed 0.5.30 on my HOOBS server but the visual method of configuring the plugin doesn't present me with a field for API Key nor Key ID, and if I try to use the Advanced method to enter them manually those lines remain gray, and when I save it those lines are removed. Is there anything else I can do?

**Comment by ourstanley** [comment]
OK, so I realized that when using TextEdit the double quotes I'd put in were 'slanted' rather than straight. I've copy pasted the double quotes from else where in the configuration and it seems to have recognized things. Now I just have to leave some time with the bridge stopped before trying it as the log file shows I've had too many failed attempts and my account is temporarily locked.

**Comment by jfarmer08** [comment]
That's good to know. I will look at hoobs soon as I can.

**Comment by jfarmer08** [comment]
https://github.com/jfarmer08/homebridge-wyze-smart-home/releases/tag/v0.5.30
