### ISSUE TITLE
Lock status doesn't update if manually unlocked/locked or unlocked/locked in Wyze app.

### ISSUE THREAD

**Issue by xenonaxel** [jfarmer08/homebridge-wyze-smart-home#135]
**Describe The Bug:**
When I unlock/lock the Wyze Lock from the Wyze app or manually Homekit does not reflect the change unless I refresh and I do not get a notification

**To Reproduce:**
I tried it as a child bridge and not and still see the same results. 

**Expected behavior:**
I should receive a notification when I manually unlock/lock or within the app. 
I lurked around and found this plugin. This exhibits the expected behavior but it no longer works due to the API creds.
https://github.com/RMCob/homebridge-wyze-connected-home-op

**Logs:**

There are no logs from the Wyze plugin from when I unlock/lock via app or manually.

**Plugin Config:**

        {
            "name": "Wyze",
            "username": "john.smith@gmail.com",
            "password": "password",
            "keyId": " api",
            "apiKey": "api",
            "refreshInterval": 60000,
            "entryExitDelay": 30,
            "showAdvancedOptions": true,
            "logging": "debug",
            "excludeMacAddress": false,
            "excludedeviceType": true,
            "filterDeviceTypeList": [
                "Camera"
            ],
            "platform": "WyzeSmartHome",
            "_bridge": {
                "username": "mac",
                "port": 23423
            }
        },
**Screenshots:**

**Environment:**

* **Plugin Version**:
Homebridge 1.6.1
Node v18.16.0
Npm 9.5.1
Debian

**Comment by xenonaxel** [comment]
Update. It will notify me. About 10-15 min after I lock/unlock it manually or through the wyze app. Is there a way to update the polling requests on the status for the lock and contact sensor?

**Comment by VonSquid** [comment]
Same for me.
And when controlling Wyze Lock via the Home app, the lock will change state just fine, but displays the Unlocking... or Locking... status until the app is refreshed.

![IMG_6054](https://github.com/jfarmer08/homebridge-wyze-smart-home/assets/141510953/30f558de-d9af-4110-b666-df2ac682f19e)

**Comment by carTloyal123** [comment]
@xenonaxel would you try to change your plugin configuration refresh interval from 60000 to 3000 and then see how it responds? This may be a refresh interval problem or possibly an api update of some kind that hasn't been addressed yet. Might also be an updated homebridge api under the hood or something. This one should be easy to debug.

**Comment by carTloyal123** [comment]
@VonSquid please try the above as well if you can by changing the refresh interval to something quite small about 3000 or so.

**Comment by xenonaxel** [comment]
@carTloyal123 Hey, I changed it to 3000. In the logs it looks like it queries the API more frequently but the status still doesn't update for quite some time. When I get home today I can grab the logs and upload them. The contact sensor that also gets created doesn't appear to ever change either.

**Comment by carTloyal123** [comment]
Yeah the full log would be great here and we can assess once the logs are in. I have a wyze lock and haven't had issues thus far so I am curious whats going on here

**Comment by VonSquid** [comment]
I've tried various refresh intervals, including 3000.  Currently have it set to 10000.  The stuck status problem seems less prevalent now, but overall operation is still inconsistent.  

- When commanding a lock or unlock state change, I see the Wyze app always reflects the correct lock position.  The lock status shown on the Home app (and mirrored in Homebridge (Hoobs in my case)) may or may not be correct.  Or may be correct for about a minute, then switch states and tell lies.
- When manually locking/unlocking, the Wyze app responds appropriately, but there is no change in the Home app (nor Homebridge).
- I have two identical Wyze locks, connected to a single Wyze Bridge.  When adding them into my Homekit, sometimes one or both with onboard as a **contact sensor** instead of a **door lock,** which makes control more difficult.  And the device type will vary depending on which Home device I look at (see attached screen shots for iOS vs macOS).
- I deleted and re-added one of the locks via the Wyze app and it onboarded as a contact sensor again.  And didn't show battery status, whereas the other lock showed as a lock and had battery status.

Looking at the log file (also attached), there are some errors present and one WARNING that point to a missing json file... maybe this will help troubleshoot.

Lastly, I was using the _homebridge-wyze-connected-home-op_ bridge for about a year previously with no problems until the API thing killed it.
[Hoobs_Log.txt](https://github.com/jfarmer08/homebridge-wyze-smart-home/files/12296019/Hoobs_Log.txt)
![Wyze Bridge](https://github.com/jfarmer08/homebridge-wyze-smart-home/assets/141510953/e6c58bca-2db9-4fbc-88ae-f8c8295619f2)

**Comment by xenonaxel** [comment]
@carTloyal123 Attached are the logs. I did get notified that it was locked about 2 minutes after I locked it which was an improvement. But for as often as it's refreshing devices. I feel like it should be almost instant.
[homebridge.log(1).txt](https://github.com/jfarmer08/homebridge-wyze-smart-home/files/12297747/homebridge.log.1.txt)

**Comment by carTloyal123** [comment]
Thanks to both of you for sending in logs and providing much needed extra info here. I will look at this over the next few days. Looks like some changes have been made since I last looked at the lock so I will catch up and hopefully find something. A not elegant solution for now just to try would be to uninstall the plugin and reinstall it. Might be some weird thing with the cached devices but I doubt it. If either of you are free/available to do a reinstall that would be great.

**Comment by jfarmer08** [comment]
Polling to fast will cause your account to be lock. I suggest turning it back.

**Comment by xenonaxel** [comment]
@carTloyal123 I actually just completely migrated my homebridge setup recently from one computer to another and the problem still occurred.

**Comment by xenonaxel** [comment]
@carTloyal123 It looks like it also affects the wyze switch as well. It doesn't update when I manually turn the switch on. Not sure if that helps you track down the issue but it's something I've noticed.

**Comment by xenonaxel** [comment]
@carTloyal123 Some strange behavior I noticed. So it does get the right status every 60 seconds but it isn't updating in HomeKit. If I reload the accessory page in homebridge ui it updates and notifies me. But otherwise it just never updates. Very strange. I hope that makes sense.

**Comment by jfarmer08** [comment]
New version is ready for testing

**Comment by VonSquid** [comment]
New version is working much better for me.  Homekit control and alerts work fine.  Status can get hung in "updating..." sometimes if the lock is manually controlled.
 
The biggest remaining issue for me, is that when I import the Wyze Locks into Homekit, they still onboard as **contact sensors** with associated locks (see screenshot)... should be the reversed.  If you expand the device, it will show the lock, but it's hiding behind the contact sensor.  

I appreciate the work here.

![IMG_6352](https://github.com/jfarmer08/homebridge-wyze-smart-home/assets/141510953/79370ea4-6b2b-47c4-b0cb-21472f121356)

**Comment by jfarmer08** [comment]
This is how my locks look in the system. 


![image](https://github.com/jfarmer08/homebridge-wyze-smart-home/assets/18117255/8a5c8ac1-fada-4b9b-9328-bce97b9d04a7)

**Comment by VonSquid** [comment]
Yours looks correct. Mine appears like this:On Nov 6, 2023, at 05:06, Farmer ***@***.***> wrote:﻿
This is how my locks look in the system.

**Comment by VonSquid** [comment]
Yours looks correct.  Mine looks like this:

![Lock](https://github.com/jfarmer08/homebridge-wyze-smart-home/assets/141510953/64814b5d-70cf-4ac6-b1a9-02257f9bc327)

**Comment by jfarmer08** [comment]
Have you tried to clear the cache and re-add it?  Worse case. I don't know if any other settings.
