### ISSUE TITLE
Please Add Support for Wyze Video Doorbell Pro, GW_BE1

### ISSUE THREAD

**Issue by dan0-gh** [jfarmer08/homebridge-wyze-smart-home#182]
Is your feature request related to a problem? Please describe:

Getting persistent messages in logs, "[Wyze] Camera (Model: GW_BE1 (Mac: GW_BE1_xx (Name: Doorbell) not supported submit a request to https://github.com/jfarmer08/homebridge-wyze-smart-home/issues to have it added. If no issues are found"

Describe the solution you'd like:

Please add support for Wyze Video Doorbell Pro, GW_BE1

Describe alternatives you've considered:

None

Additional context:

[Wyze Video Doorbell Pro](https://www.wyze.com/products/wyze-video-doorbell-pro)

**Comment by matthewmspace** [comment]
I second this, please add support for the Doorbell Pro.

**Comment by carsonloyaltrimble** [comment]
The doorbell pro might be able to be supported in this plugin but in limited capacity.

On the other hand, I have been working on reverse engineering the doorbell pro so you can get your video feed outside of the wyze app ie in Homekit or some other bridge. I have completed the reversing part and am now working through integrating with repos like docker-wyze-bridge so that my work is easily accessible. My project is here: [Cryze](https://github.com/carTloyal123/cryze) 

@jfarmer08 do you have input on this or can we close this as out of scope? From what I can tell other cameras can be used in this plugin with limited functions like on/off or on/off according to detection state but the doorbell is fundamentally different in that there is no on/off state. The detection part might be possible to keep in this plugin but I would have to see if it is feasible and/or uses similar apis as the other cameras.

**Comment by carTloyal123** [comment]
The doorbell pro might be able to be supported in this plugin but in limited capacity.

On the other hand, I have been working on reverse engineering the doorbell pro so you can get your video feed outside of the wyze app ie in Homekit or some other bridge. I have completed the reversing part and am now working through integrating with repos like docker-wyze-bridge so that my work is easily accessible. My project is here: [Cryze](https://github.com/carTloyal123/cryze) 

@jfarmer08 do you have input on this or can we close this as out of scope? From what I can tell other cameras can be used in this plugin with limited functions like on/off or on/off according to detection state but the doorbell is fundamentally different in that there is no on/off state. The detection part might be possible to keep in this plugin but I would have to see if it is feasible and/or uses similar apis as the other cameras.

**Comment by jfarmer08** [comment]
I have not looked at the Pro version, so I am not sure what is available. This ticket should be in https://github.com/jfarmer08/wyze-api

**Comment by carTloyal123** [comment]
Closed as the request should go in https://github.com/jfarmer08/wyze-api as noted by @jfarmer08 

Feel free to reopen over there @dan0-gh to make sure this stays on the list of wanted features, thanks!
