### ISSUE TITLE
SMS MFA support

### ISSUE THREAD

**Issue by justin-bond** [jfarmer08/homebridge-wyze-smart-home#65]
**Is your feature request related to a problem? Please describe:**
- There is MFA support, but only for "authenticator app"

**Describe the solution you'd like:**
- Would like MFA support for "Text (SMS)"

**Additional context:**
- Currently MFA for SMS works until you log into the mobile app using SMS MFA and homebridge no longer has access

**Comment by carTloyal123** [comment]
MFA support over text is tricky because you have to enter the code after the plugin has started which is annoying. Best option is to simply enable 2FA with an auth app to get up and running. This can also be overcome with some infrastructure changes like enabling you to enter your private seed for MFA and let the plugin generate the MFA code but that is not a top priority when you can use an MFA app instead. I am curious what @jfarmer08 thinks about this and if there is a solution possible that I am missing. This could be solved by some hackery like checking a file every 5 seconds for you to enter the SMS code but that is still annoying. We will see!

**Comment by jfarmer08** [comment]
I have been looking at add support for homebridge plugin ui. This would allow support for entering your sms code before the plugin starts. I have stayed playing in the rebase branch if want to take a look. I am not a front end developer so it might be out of my expertise. 

https://github.com/homebridge/plugin-ui-utils

**Comment by davedudek** [comment]
I'm having issues with this as well - it says  [Wyze] Error, refreshing access token and trying again

**Comment by jfarmer08** [comment]
Use MFA will no longer be needed when moving to the Wyze API Console.
